name: Keep Render AI API Awake

on:
  schedule:
    - cron: "4,9,14,19,24,29,34,39,44,49,54,59 * * * *" # Runs every 5 minutes

jobs:
  keep_awake:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render API
        run: curl -s https://innovise-ai.onrender.com/
